CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'TaskManagement') THEN
        CREATE SCHEMA "TaskManagement";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'Security') THEN
        CREATE SCHEMA "Security";
    END IF;
END $EF$;

CREATE TABLE "TaskManagement"."BacklogStatus" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Order" integer NOT NULL,
    "BadgeColor" text NOT NULL,
    "IsClosed" boolean NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_BacklogStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."Enterprise" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Enterprise" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."HourType" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Scope" text NOT NULL,
    "Order" integer NOT NULL,
    "BadgeColor" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_HourType" PRIMARY KEY ("Id")
);

CREATE TABLE "Security"."Menu" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Icon" integer NOT NULL,
    "Page" text NOT NULL,
    "Parent" bigint NULL,
    "Order" integer NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Menu" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."Priority" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "BadgeColor" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Priority" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."ProjectStatus" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Order" integer NOT NULL,
    "BadgeColor" text NOT NULL,
    "IsClosed" boolean NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_ProjectStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."RequirementStatus" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Order" integer NOT NULL,
    "BadgeColor" text NOT NULL,
    "IsClosed" boolean NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_RequirementStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "Security"."Role" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."TaskBugStatus" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Order" integer NOT NULL,
    "BadgeColor" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TaskBugStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."TaskDevelopmentPhase" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Order" integer NOT NULL,
    "BadgeColor" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TaskDevelopmentPhase" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."TaskStatus" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "Order" integer NOT NULL,
    "BadgeColor" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TaskStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "Security"."User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "Password" text NOT NULL,
    "JobTitle" text NOT NULL,
    "AvatarFileName" text NULL,
    "AvatarFilePath" text NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

CREATE TABLE "TaskManagement"."Customer" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "EnterpriseId" bigint NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Customer" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Customer_Enterprise_EnterpriseId" FOREIGN KEY ("EnterpriseId") REFERENCES "TaskManagement"."Enterprise" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Security"."RoleMenu" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" bigint NOT NULL,
    "MenuId" bigint NOT NULL,
    "CanView" boolean NOT NULL,
    "CanCreate" boolean NOT NULL,
    "CanEdit" boolean NOT NULL,
    "CanDelete" boolean NOT NULL,
    "CanRegisterHours" boolean NOT NULL,
    "CanFinalize" boolean NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_RoleMenu" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleMenu_Menu_MenuId" FOREIGN KEY ("MenuId") REFERENCES "Security"."Menu" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RoleMenu_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Security"."Role" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Security"."UserRole" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "RoleId" bigint NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserRole_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Security"."Role" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRole_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Security"."UserTimeOff" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "Type" smallint NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Hours" numeric NOT NULL,
    "Description" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_UserTimeOff" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserTimeOff_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."BacklogItem" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "BacklogStatusId" bigint NOT NULL,
    "CustomerId" bigint NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_BacklogItem" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BacklogItem_BacklogStatus_BacklogStatusId" FOREIGN KEY ("BacklogStatusId") REFERENCES "TaskManagement"."BacklogStatus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_BacklogItem_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "TaskManagement"."Customer" ("Id")
);

CREATE TABLE "TaskManagement"."Project" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "CustomerId" bigint NOT NULL,
    "ProjectStatusId" bigint NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NULL,
    "ActualEndDate" timestamp with time zone NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Project" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Project_Customer_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "TaskManagement"."Customer" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Project_ProjectStatus_ProjectStatusId" FOREIGN KEY ("ProjectStatusId") REFERENCES "TaskManagement"."ProjectStatus" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."Requirement" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NOT NULL,
    "ProjectId" bigint NOT NULL,
    "Scope" text NOT NULL,
    "RequirementStatusId" bigint NOT NULL,
    "PriorityId" bigint NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NULL,
    "ActualEndDate" timestamp with time zone NULL,
    "RequesterName" text NOT NULL,
    "RequestDate" timestamp with time zone NOT NULL,
    "ImpactedSystems" text NOT NULL,
    "FreshDeskTicketNumber" text NULL,
    "IsWithinOriginalScope" boolean NOT NULL,
    "ScopeChangeReason" smallint NULL,
    "IsProductionReprocess" boolean NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Requirement" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Requirement_Priority_PriorityId" FOREIGN KEY ("PriorityId") REFERENCES "TaskManagement"."Priority" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Requirement_Project_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "TaskManagement"."Project" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Requirement_RequirementStatus_RequirementStatusId" FOREIGN KEY ("RequirementStatusId") REFERENCES "TaskManagement"."RequirementStatus" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."Attachment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RequirementId" bigint NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Attachment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attachment_Requirement_RequirementId" FOREIGN KEY ("RequirementId") REFERENCES "TaskManagement"."Requirement" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."Task" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RequirementId" bigint NOT NULL,
    "UserId" bigint NULL,
    "TimeEstimationHours" numeric NOT NULL,
    "Description" text NOT NULL,
    "PriorityId" bigint NOT NULL,
    "TaskStatusId" bigint NOT NULL,
    "DevelopmentPhaseId" bigint NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NULL,
    "ActualEndDate" timestamp with time zone NULL,
    "QaEnteredAt" timestamp with time zone NULL,
    "IsWithinOriginalScope" boolean NOT NULL,
    "ScopeChangeReason" smallint NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_Task" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Task_Priority_PriorityId" FOREIGN KEY ("PriorityId") REFERENCES "TaskManagement"."Priority" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Task_Requirement_RequirementId" FOREIGN KEY ("RequirementId") REFERENCES "TaskManagement"."Requirement" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Task_TaskDevelopmentPhase_DevelopmentPhaseId" FOREIGN KEY ("DevelopmentPhaseId") REFERENCES "TaskManagement"."TaskDevelopmentPhase" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Task_TaskStatus_TaskStatusId" FOREIGN KEY ("TaskStatusId") REFERENCES "TaskManagement"."TaskStatus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Task_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("Id")
);

CREATE TABLE "TaskManagement"."TaskBug" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "RequirementId" bigint NOT NULL,
    "TaskId" bigint NULL,
    "Description" text NOT NULL,
    "TaskBugStatusId" bigint NOT NULL,
    "ReportedByUserId" bigint NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TaskBug" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskBug_Requirement_RequirementId" FOREIGN KEY ("RequirementId") REFERENCES "TaskManagement"."Requirement" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskBug_Task_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskManagement"."Task" ("Id"),
    CONSTRAINT "FK_TaskBug_TaskBugStatus_TaskBugStatusId" FOREIGN KEY ("TaskBugStatusId") REFERENCES "TaskManagement"."TaskBugStatus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskBug_User_ReportedByUserId" FOREIGN KEY ("ReportedByUserId") REFERENCES "Security"."User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."TaskNote" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" bigint NOT NULL,
    "Content" text NOT NULL,
    "AuthorUserId" bigint NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TaskNote" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskNote_Task_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskManagement"."Task" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskNote_User_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES "Security"."User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."TaskStatusHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskId" bigint NOT NULL,
    "TaskStatusId" bigint NOT NULL,
    "PreviousTaskStatusId" bigint NULL,
    "Reason" text NOT NULL,
    "ChangedByUserId" bigint NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TaskStatusHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskStatusHistory_Task_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskManagement"."Task" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskStatusHistory_TaskStatus_PreviousTaskStatusId" FOREIGN KEY ("PreviousTaskStatusId") REFERENCES "TaskManagement"."TaskStatus" ("Id"),
    CONSTRAINT "FK_TaskStatusHistory_TaskStatus_TaskStatusId" FOREIGN KEY ("TaskStatusId") REFERENCES "TaskManagement"."TaskStatus" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TaskStatusHistory_User_ChangedByUserId" FOREIGN KEY ("ChangedByUserId") REFERENCES "Security"."User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."TimeLog" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ExecutionDate" timestamp with time zone NOT NULL,
    "UsedHours" numeric NOT NULL,
    "ProgressPercent" numeric NOT NULL,
    "TaskId" bigint NOT NULL,
    "HourTypeId" bigint NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TimeLog" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TimeLog_HourType_HourTypeId" FOREIGN KEY ("HourTypeId") REFERENCES "TaskManagement"."HourType" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TimeLog_Task_TaskId" FOREIGN KEY ("TaskId") REFERENCES "TaskManagement"."Task" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TimeLog_User_UserId" FOREIGN KEY ("UserId") REFERENCES "Security"."User" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskManagement"."TaskBugAttachment" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "TaskBugId" bigint NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "RowStatus" smallint NOT NULL,
    "CreatedBy" bigint NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "UpdatedBy" bigint NULL,
    "Updated" timestamp with time zone NULL,
    CONSTRAINT "PK_TaskBugAttachment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskBugAttachment_TaskBug_TaskBugId" FOREIGN KEY ("TaskBugId") REFERENCES "TaskManagement"."TaskBug" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Attachment_RequirementId" ON "TaskManagement"."Attachment" ("RequirementId");

CREATE INDEX "IX_BacklogItem_BacklogStatusId" ON "TaskManagement"."BacklogItem" ("BacklogStatusId");

CREATE INDEX "IX_BacklogItem_CustomerId" ON "TaskManagement"."BacklogItem" ("CustomerId");

CREATE INDEX "IX_Customer_EnterpriseId" ON "TaskManagement"."Customer" ("EnterpriseId");

CREATE INDEX "IX_Project_CustomerId" ON "TaskManagement"."Project" ("CustomerId");

CREATE INDEX "IX_Project_ProjectStatusId" ON "TaskManagement"."Project" ("ProjectStatusId");

CREATE INDEX "IX_Requirement_PriorityId" ON "TaskManagement"."Requirement" ("PriorityId");

CREATE INDEX "IX_Requirement_ProjectId" ON "TaskManagement"."Requirement" ("ProjectId");

CREATE INDEX "IX_Requirement_RequirementStatusId" ON "TaskManagement"."Requirement" ("RequirementStatusId");

CREATE INDEX "IX_RoleMenu_MenuId" ON "Security"."RoleMenu" ("MenuId");

CREATE INDEX "IX_RoleMenu_RoleId" ON "Security"."RoleMenu" ("RoleId");

CREATE INDEX "IX_Task_DevelopmentPhaseId" ON "TaskManagement"."Task" ("DevelopmentPhaseId");

CREATE INDEX "IX_Task_PriorityId" ON "TaskManagement"."Task" ("PriorityId");

CREATE INDEX "IX_Task_RequirementId" ON "TaskManagement"."Task" ("RequirementId");

CREATE INDEX "IX_Task_TaskStatusId" ON "TaskManagement"."Task" ("TaskStatusId");

CREATE INDEX "IX_Task_UserId" ON "TaskManagement"."Task" ("UserId");

CREATE INDEX "IX_TaskBug_ReportedByUserId" ON "TaskManagement"."TaskBug" ("ReportedByUserId");

CREATE INDEX "IX_TaskBug_RequirementId" ON "TaskManagement"."TaskBug" ("RequirementId");

CREATE INDEX "IX_TaskBug_TaskBugStatusId" ON "TaskManagement"."TaskBug" ("TaskBugStatusId");

CREATE INDEX "IX_TaskBug_TaskId" ON "TaskManagement"."TaskBug" ("TaskId");

CREATE INDEX "IX_TaskBugAttachment_TaskBugId" ON "TaskManagement"."TaskBugAttachment" ("TaskBugId");

CREATE INDEX "IX_TaskNote_AuthorUserId" ON "TaskManagement"."TaskNote" ("AuthorUserId");

CREATE INDEX "IX_TaskNote_TaskId" ON "TaskManagement"."TaskNote" ("TaskId");

CREATE INDEX "IX_TaskStatusHistory_ChangedByUserId" ON "TaskManagement"."TaskStatusHistory" ("ChangedByUserId");

CREATE INDEX "IX_TaskStatusHistory_PreviousTaskStatusId" ON "TaskManagement"."TaskStatusHistory" ("PreviousTaskStatusId");

CREATE INDEX "IX_TaskStatusHistory_TaskId" ON "TaskManagement"."TaskStatusHistory" ("TaskId");

CREATE INDEX "IX_TaskStatusHistory_TaskStatusId" ON "TaskManagement"."TaskStatusHistory" ("TaskStatusId");

CREATE INDEX "IX_TimeLog_HourTypeId" ON "TaskManagement"."TimeLog" ("HourTypeId");

CREATE INDEX "IX_TimeLog_TaskId" ON "TaskManagement"."TimeLog" ("TaskId");

CREATE INDEX "IX_TimeLog_UserId" ON "TaskManagement"."TimeLog" ("UserId");

CREATE INDEX "IX_UserRole_RoleId" ON "Security"."UserRole" ("RoleId");

CREATE INDEX "IX_UserRole_UserId" ON "Security"."UserRole" ("UserId");

CREATE INDEX "IX_UserTimeOff_UserId" ON "Security"."UserTimeOff" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260813211139_InitialCreate', '6.0.25');

COMMIT;

