// <auto-generated />
using System;
using GestionProyectos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionProyectos.Data.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.Menu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("Icon")
                        .HasColumnType("integer")
                        .HasColumnName("Icon");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Page");

                    b.Property<long?>("Parent")
                        .HasColumnType("bigint")
                        .HasColumnName("Parent");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Menu", "Security");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Role", "Security");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.RoleMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean")
                        .HasColumnName("CanCreate");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean")
                        .HasColumnName("CanDelete");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("boolean")
                        .HasColumnName("CanEdit");

                    b.Property<bool>("CanFinalize")
                        .HasColumnType("boolean")
                        .HasColumnName("CanFinalize");

                    b.Property<bool>("CanRegisterHours")
                        .HasColumnType("boolean")
                        .HasColumnName("CanRegisterHours");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean")
                        .HasColumnName("CanView");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<long>("MenuId")
                        .HasColumnType("bigint")
                        .HasColumnName("MenuId");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMenu", "Security");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AvatarFileName")
                        .HasColumnType("text")
                        .HasColumnName("AvatarFileName");

                    b.Property<string>("AvatarFilePath")
                        .HasColumnType("text")
                        .HasColumnName("AvatarFilePath");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("JobTitle");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("LastName");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("User", "Security");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("RoleId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", "Security");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.UserTimeOff", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<decimal>("Hours")
                        .HasColumnType("numeric")
                        .HasColumnName("Hours");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserTimeOff", "Security");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FilePath");

                    b.Property<long>("RequirementId")
                        .HasColumnType("bigint")
                        .HasColumnName("RequirementId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.ToTable("Attachment", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.BacklogItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BacklogStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("BacklogStatusId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<long?>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("BacklogStatusId");

                    b.HasIndex("CustomerId");

                    b.ToTable("BacklogItem", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.BacklogStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsClosed");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("BacklogStatus", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<long>("EnterpriseId")
                        .HasColumnType("bigint")
                        .HasColumnName("EnterpriseId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("EnterpriseId");

                    b.ToTable("Customer", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Enterprise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Enterprise", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.HourType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Scope");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("HourType", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Priority", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("Priority", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ActualEndDate");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<long>("ProjectStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProjectStatusId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProjectStatusId");

                    b.ToTable("Project", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.ProjectStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsClosed");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatus", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Requirement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ActualEndDate");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<string>("FreshDeskTicketNumber")
                        .HasColumnType("text")
                        .HasColumnName("FreshDeskTicketNumber");

                    b.Property<string>("ImpactedSystems")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ImpactedSystems");

                    b.Property<bool>("IsProductionReprocess")
                        .HasColumnType("boolean")
                        .HasColumnName("IsProductionReprocess");

                    b.Property<bool>("IsWithinOriginalScope")
                        .HasColumnType("boolean")
                        .HasColumnName("IsWithinOriginalScope");

                    b.Property<long>("PriorityId")
                        .HasColumnType("bigint")
                        .HasColumnName("PriorityId");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("ProjectId");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RequestDate");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("RequesterName");

                    b.Property<long>("RequirementStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("RequirementStatusId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Scope");

                    b.Property<short?>("ScopeChangeReason")
                        .HasColumnType("smallint")
                        .HasColumnName("ScopeChangeReason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RequirementStatusId");

                    b.ToTable("Requirement", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.RequirementStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("IsClosed");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("RequirementStatus", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ActualEndDate");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<long>("DevelopmentPhaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("DevelopmentPhaseId");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<bool>("IsWithinOriginalScope")
                        .HasColumnType("boolean")
                        .HasColumnName("IsWithinOriginalScope");

                    b.Property<long>("PriorityId")
                        .HasColumnType("bigint")
                        .HasColumnName("PriorityId");

                    b.Property<DateTime?>("QaEnteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("QaEnteredAt");

                    b.Property<long>("RequirementId")
                        .HasColumnType("bigint")
                        .HasColumnName("RequirementId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<short?>("ScopeChangeReason")
                        .HasColumnType("smallint")
                        .HasColumnName("ScopeChangeReason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<long>("TaskStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskStatusId");

                    b.Property<decimal>("TimeEstimationHours")
                        .HasColumnType("numeric")
                        .HasColumnName("TimeEstimationHours");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DevelopmentPhaseId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("TaskStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Task", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskBug", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("EndDate");

                    b.Property<long>("ReportedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReportedByUserId");

                    b.Property<long>("RequirementId")
                        .HasColumnType("bigint")
                        .HasColumnName("RequirementId");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("StartDate");

                    b.Property<long>("TaskBugStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskBugStatusId");

                    b.Property<long?>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("RequirementId");

                    b.HasIndex("TaskBugStatusId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskBug", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskBugAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FileName");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("FilePath");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<long>("TaskBugId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskBugId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("TaskBugId");

                    b.ToTable("TaskBugAttachment", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskBugStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("TaskBugStatus", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskDevelopmentPhase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("TaskDevelopmentPhase", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("AuthorUserId");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Content");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskNote", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BadgeColor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("BadgeColor");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Description");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("Order");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.ToTable("TaskStatus", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ChangedByUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ChangedByUserId");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<long?>("PreviousTaskStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("PreviousTaskStatusId");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Reason");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskId");

                    b.Property<long>("TaskStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskStatusId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("PreviousTaskStatusId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("TaskStatusHistory", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TimeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Created");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExecutionDate");

                    b.Property<long>("HourTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("HourTypeId");

                    b.Property<decimal>("ProgressPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("ProgressPercent");

                    b.Property<short>("RowStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("RowStatus");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskId");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Updated");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("UpdatedBy");

                    b.Property<decimal>("UsedHours")
                        .HasColumnType("numeric")
                        .HasColumnName("UsedHours");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("HourTypeId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TimeLog", "TaskManagement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.RoleMenu", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.Security.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.Security.Role", null)
                        .WithMany("RoleMenus")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.UserRole", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.Security.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.Security.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.UserTimeOff", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.Security.User", "User")
                        .WithMany("TimeOffs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Attachment", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Requirement", "Requirement")
                        .WithMany("Attachments")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.BacklogItem", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.BacklogStatus", "BacklogStatus")
                        .WithMany("BacklogItems")
                        .HasForeignKey("BacklogStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("BacklogStatus");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Customer", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Enterprise", "Enterprise")
                        .WithMany("Customers")
                        .HasForeignKey("EnterpriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enterprise");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Project", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.ProjectStatus", "ProjectStatus")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ProjectStatus");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Requirement", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Priority", "Priority")
                        .WithMany("Requirements")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Project", "Project")
                        .WithMany("Requirements")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.RequirementStatus", "RequirementStatus")
                        .WithMany("Requirements")
                        .HasForeignKey("RequirementStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");

                    b.Navigation("Project");

                    b.Navigation("RequirementStatus");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Task", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.TaskDevelopmentPhase", "DevelopmentPhase")
                        .WithMany("Tasks")
                        .HasForeignKey("DevelopmentPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Priority", "Priority")
                        .WithMany("Tasks")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Requirement", "Requirement")
                        .WithMany("Tasks")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.TaskStatus", "TaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("DevelopmentPhase");

                    b.Navigation("Priority");

                    b.Navigation("Requirement");

                    b.Navigation("TaskStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskBug", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.Security.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Requirement", "Requirement")
                        .WithMany("Bugs")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.TaskBugStatus", "TaskBugStatus")
                        .WithMany("Bugs")
                        .HasForeignKey("TaskBugStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Task", "Task")
                        .WithMany("Bugs")
                        .HasForeignKey("TaskId");

                    b.Navigation("ReportedByUser");

                    b.Navigation("Requirement");

                    b.Navigation("Task");

                    b.Navigation("TaskBugStatus");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskBugAttachment", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.TaskBug", "TaskBug")
                        .WithMany("Attachments")
                        .HasForeignKey("TaskBugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskBug");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskNote", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.Security.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Task", "Task")
                        .WithMany("Notes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskStatusHistory", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.Security.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.TaskStatus", "PreviousTaskStatus")
                        .WithMany("PreviousStatusHistoryEntries")
                        .HasForeignKey("PreviousTaskStatusId");

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Task", "Task")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.TaskStatus", "TaskStatus")
                        .WithMany("StatusHistoryEntries")
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("PreviousTaskStatus");

                    b.Navigation("Task");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TimeLog", b =>
                {
                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.HourType", "HourType")
                        .WithMany("TimeLogs")
                        .HasForeignKey("HourTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.TaskManagement.Task", "Task")
                        .WithMany("TimeLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionProyectos.Data.Entities.Security.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HourType");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.Role", b =>
                {
                    b.Navigation("RoleMenus");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.Security.User", b =>
                {
                    b.Navigation("TimeOffs");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.BacklogStatus", b =>
                {
                    b.Navigation("BacklogItems");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Enterprise", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.HourType", b =>
                {
                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Priority", b =>
                {
                    b.Navigation("Requirements");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Project", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Requirement", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Bugs");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.RequirementStatus", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.Task", b =>
                {
                    b.Navigation("Bugs");

                    b.Navigation("Notes");

                    b.Navigation("StatusHistory");

                    b.Navigation("TimeLogs");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskBug", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskBugStatus", b =>
                {
                    b.Navigation("Bugs");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskDevelopmentPhase", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GestionProyectos.Data.Entities.TaskManagement.TaskStatus", b =>
                {
                    b.Navigation("PreviousStatusHistoryEntries");

                    b.Navigation("StatusHistoryEntries");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
